-------------------------------------------------------------------
--
-- Fichier              :       EMAILING_KSL_COURRIER.CP
-- Auteur               :       Fabry JF
-- Date                 :       02/01/2025
--
-- Commentaires         :      
--
-- Procedures           :       
--------------------------------------------------------------------

--------------------------------------------------------------------
--
-- Procedure            :       sysadm.
-- Auteur               :       Fabry JF
-- Date                 :       25/04/2023
-- Libelle              :        
-- Commentaires         :       Ramène la liste des variable XML
-- References           :       
--
-- Arguments            :       
--
-- Retourne             :       Rien
--
-------------------------------------------------------------------


